CREATE TABLE city (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  created_at DATETIME NOT NULL DEFAULT NOW(),
  updated_at DATETIME NULL,
  name VARCHAR(255) NOT NULL,

  PRIMARY KEY (id),
  UNIQUE KEY (name)
) CHARSET utf8;
